apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: tcp-sync-response-pipe
spec:
  integration:
    dependencies:
      - "github:fkdraeb/processor/e54de07352"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: spring-rabbitmq-source
    properties:
      host: production-rabbitmqcluster-nodes
      port: 5672
      username: guest
      password: guest
      queues: tcp_sync_queue
      exchangeName: amq.direct
  steps:
    - ref: 
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: tcp-process-patientid-action
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: hip-mysql-sink
    properties:
      #query: SELECT * FROM Patients WHERE patient_id LIKE :#patientId
      query: CALL patient_data_from_id (:#patientId)
      username: root
      password: password
      serverName: mysql
      serverPort: 3306
      databaseName: HIP