apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: tcp-sync-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: netty-source
    properties:
      protocol: tcp
      host: 0.0.0.0
      port: 8094
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: hip-rabbitmq-sink
    properties:
      exchangeName: amq.direct
      host: production-rabbitmqcluster-nodes
      port: 5672
      username: guest
      password: guest
      routingKey: tcp_sync_queue