apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: hip-rabbitmq-to-tcp-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: hip-rabbitmq-source
    properties:
      host: production-rabbitmqcluster-nodes
      port: 5672
      username: guest
      password: guest
      exchangeName: hip.tcp
      queues: tcp_outbound_queue
      durable: true
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: hip-hl7messagepreparation-processor-action
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: hip-netty-sink
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: hip-updateeventstatus-processor-action
  errorHandler:
    sink:
      endpoint:
        ref:
          kind: Kamelet
          apiVersion: camel.apache.org/v1
          name: hip-updateeventstatus-processor-action