apiVersion: v1
kind: Service
metadata:
  name: netty-service
  namespace: camel
spec:
  type: NodePort
  selector:
    camel.apache.org/integration: tcp-inbound-handler
  ports:
  - protocol: TCP
    name: async-flow-port
    port: 8093       # The port your service will be exposed on internally
    targetPort: 8093 # The port your application listens on
    nodePort: 30093  # The port to access your service externally
  - protocol: TCP
    name: sync-flow-port
    port: 8094       
    targetPort: 8094 
    nodePort: 30094  