apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: tcp-async-pipe
spec:
  integration:
    dependencies:
      - "github:fkdraeb/processor/a8acdcc8a6"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: netty-source
    properties:
      protocol: tcp
      host: 0.0.0.0
      port: 8093
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: hip-async-rabbitmq-sink
    properties:
      exchangeName: amq.direct
      host: production-rabbitmqcluster-nodes
      port: 5672
      username: guest
      password: guest
      routingKey: tcp_async_queue
      disableReplyTo: true

