apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: netty-http-log-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: netty-http-inbound-source
    properties:
      host: http://0.0.0.0
      port: 8092
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
    properties:
      level: INFO

